algoritmo "Contador1a5"
var
   cont: inteiro
inicio
      EscrevaL("-------------")
      EscrevaL(" DE 1 ate 5 ")
      EscrevaL("-------------")
      Para cont <- 1 ate 5 passo 1 faca
           EscrevaL(" ",cont)
      FimPara
      EscrevaL("-------------")
      EscrevaL(" DE 5 ate 1 ")
      EscrevaL("-------------")
      Para cont <- 5 ate 1 passo -1 faca
           EscrevaL(" ",cont)
      FimPara
fimalgoritmo
